name: E2E on Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E on Chrome headless
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true